### ISSUE TITLE
Koreader sync on Kindle does not work

### ISSUE THREAD

**Issue by htrembler-lgtm** [grimmory-tools/grimmory#414]
### What Went Wrong?

I am intending to use Grimmory as the sync server between Koreader on my phone and Koreader on my jailbroken Kindle. I am able to connect to the sync server from Koreader on my phone and it works great to sync progress with Grimmory, but when I attempt to log in to the sync server on my Kindle it fails with "unknown server error". It's possible I'm missing something really basic, but I cannot figure it out.

### How Can We Reproduce This?

Attempt to log into server on Kindle.
Log in fails.

### What Should Have Happened?

Koreader on Kindle should log in to sync server without issue the same way Koreader on my phone does.

### Your Setup

Grimmory Version - 2.3.0
Koreader Version - 2026.03
Phone - Samsung zFold6
Kindle - 10th Gen Oasis

### Before Submitting

- [x] I've searched existing issues and confirmed this bug hasn't been reported yet

**Comment by hobbylabbing** [comment]
Were you able to follow [these docs](https://grimmory.org/docs/integration/koreader)? I followed it today and was able to get it working on my jailbroken kindle.
Are you using a public domain or something like `localhost`?

**Comment by htrembler-lgtm** [comment]
Yeah, those are the instructions I followed to get it up and running. In Grimmory I have the server set as local-ip-number/api/koreader. I have my desktop, phone, and kindle connected with Tailscale and in Koreader connect to tailscale-ip-number/api/koreader. It works fine on my phone but will not connect on Kindle. What's weird is it worked flawlessly with Booklore, but doesn't now with Grimmory, even though everything else is set up identically.

**Comment by hobbylabbing** [comment]
Wow I did not even realize you could run tailscale on a Kindle. I don't know much about tailscale, but I would assume some sort of weird routing issue, although it is weird it worked on Booklore. 

Looks like some others in this issue were having some sort of outbound problems with tailscale on kindle: https://github.com/mitanshu7/tailscale_kual/issues/2

**Comment by htrembler-lgtm** [comment]
I thought it was pretty strange that switching to Grimmory would cause a problem. I've tried disconnecting from the tailnet and using the same ip number that is actually configured in Grimmory and it doesn't want to connect that way so I assume it's an issue with the Kindle itself, but that's getting way too in the weeds for me to mess with

**Comment by hobbylabbing** [comment]
I just tried to key in my server incorrectly on my kindle and couldn’t replicate the exact issue. For me it says `something went wrong when syncing progress`

Only other thing I could think to check is make sure the document matching is set to Binary on the kindle instead of Filename

**Comment by htrembler-lgtm** [comment]
I checked and I have the same basic problem with the OPDS server as well. I can access it through Koreader on my phone, but not on my Kindle with identical set up. I'm at kind of a loss for what could be going on

**Comment by olmet** [comment]
I have the same issue with a Pocketbook Clara.
With Booklore, synchronization with KoReader and the OPDS feature worked perfectly. Since switching to Grimmory, nothing works anymore – the server cannot be reached.

I have double-checked the exact access credentials and passwords.
Sync server address was and still is: http://192.168.21.122:8081/api/koreader
Error: "Unknown server error"

OPDS catalog: Server: connection refused
http://192.168.21.122:8081/api/v1/opds

**Comment by RockingBurn** [comment]
Since updating to 3.0 or 3.0.2 Pushing KoReadersync is not working on Kindle and Xteink x4.
ODPS ost still working. Very Strange

**Comment by htrembler-lgtm** [comment]
I was still running 2.3.0 and hoped updating would fix the issue, but I am still unable to log into the sync server on Kindle.

**Comment by RockingBurn** [comment]
I can pull but not push the progress. My x4 Koareader sync shows the remote locations still named "From: BookLore". Is there the possibility that not all chemas ?( i'm not a programmer ) have been renamed in those releases?

**Comment by ProjectMoon** [comment]
I am seeing this with latest koreader and Grimmory on a Kindle Oasis. I enabled verbose logging in KOReader since nothing shows up on the Grimmory side. I'm able to successfully log in, but cannot pull or push progress. The only relevant bit I see in koreader is:

```
05/08/26-13:24:38 DEBUG KOSyncClient:update_progress failure: "404 not expected" 
```

So it seems koreader is attempting to push to some API endpoint that Grimmory maybe does not implement yet?

**Comment by tralph3** [comment]
Same here. Used to work, and now without changing anything it doesn't anymore. I can log in, and I see in grimmory's logs the user gets authenticated, but pushing or pulling results in an error.

EDIT: Don't mind me. What actually happened is that I updated the metadata on Grimmory's side, chagning the hash of the epub, which makes it not match anymore.

**Comment by htrembler-lgtm** [comment]
This still does not work on my Kindle Oasis. I've confirmed that syncing works on the official Koreader sync servers, so it is some issue with the way the Kindle interacts with Grimmory for some reason. OPDS access also does not work.

**Comment by imnotjames** [comment]
I cannot reproduce this.  I have used a kindle paperwhite with koreader, a kobo clara bw with koreader, an Xteink 4 with crosspoint, and KOReader on Android.

Both the sync (push & pull), as well as OPDS works for all of them.

Can anyone include koreader logs / Grimmory logs?

**Comment by imnotjames** [comment]
> I can pull but not push the progress. My x4 Koareader sync shows the remote locations still named "From: BookLore". Is there the possibility that not all chemas ?( i'm not a programmer ) have been renamed in those releases?

Anything coming from Grimmory had a hard coded source.  I've fixed that.

**Comment by imnotjames** [comment]
Given that we do not have any information on what doesn't work and valid replication information I'll be closing this out.  Please feel free to open a new issue with proper replication instructions.
